image: microsoft/dotnet:latest

stages:
  - build
  - publish

build:
  stage: build
  script:
    - cd HiveThrift 
    - dotnet build

publish:
  stage: publish
  script:
    - cd HiveThrift
    - dotnet build
    - dotnet publish
    - dotnet nuget push HiveThrift/bin/Debug/*.nupkg -k $NUGET_KEY -s https://www.myget.org/F/s2/api/v2/package

